name: MinerExpansion
version: ${project.version}
main: me.minercoffee.minerexpansion.MinerExpansion
api-version: 1.18
authors: [ MinerCoffee ]
depend: [Vault]
softdepend: [PlaceholderAPI]
loadbefore: [Vault]
load: POSTWORLD
description: All in one plugin. Some it's features are better elytras, custom recipes, nightvision, custom tools, and more.
commands:
  warpgui:
    description: lists all warps!
  updatechecker:
    description: "Checks for updates"
    usage: "/<command> [players|all]"
    permission: updatechecker
  test:
    description: test flare
    usage: /<command>
  giveflare:
    description: gives a flare.
    usage: /<command> <player>
  mereload:
    description: reloads the config.
    usage: /<command>
  nv:
    description: nightvision for player.
    usage: /<command>
  slots:
    description: Slots rewards.
    usage: /<command>
  vaultbal:
    description: Player's current balance.
    usage: /<command>
  admin:
    description: Admin cmds
    usage: /<command> args
  rtp:
    description: random teleport the player.
    usage: /<command>
  givethrowingaxe:
    description: gives throwingaxe to the player.
    usage: /<command>
  givegrapplinghook:
    description: grapplinghook to transport.
    usage: /<commmand>
  giveelytra:
    description: gives custom elytra to the player.
    usage: /<command>
  supplydrop:
    description: Request a supply drop
  editsupplydrop:
    description: Edit supply drop contents
  deletesupplydrop:
    description: Delete a supply drop
  envoy:
    description: Envoy creator and configuration command
  chunkvisualizer:
    description: Set yourself on fire.
    aliases: [ cv, sc, seechunks ]
    permission: chunkvisualizer.view
    usage: type /<command> to see chunk borders.
  staffhome:
    description: The main command for staff homes!
    usage: /<command>
  warp:
    description: Warps the player to a provided warp.
  setwarp:
    description: Sets a warp loctions.
  delwarp:
    description: Deletes known warps.
permissions:
  supplydrop.use:
    default: op
  rtp.others:
    description: perms to teleport with rtp command.
    default: op
  miner.nightvision:
    description: nightvision for players
    default: op
  miner.staff:
    description: Access to reload config, withdraw, and deposit, freeze, and unfreeze.
    default: op
  miner.silk:
    description: Access to silk touch spawners.
    default: op
  chunkvisualizer.view:
    description: Gives/Grant access to chunk visualization.
    default: op
  updatechecker:
    description: Allows to use the command /updatechecker
    default: op
  updatechecker.onjoin:
    description: Sends a message on join when a new update is available
    default: op